notARepository: skip
promptToReturnFromSubprocess: false

gui:
  tabWidth: 2
  expandFocusedSidePanel: true
  expandedSidePanelWeight: 2
  mainPanelSplitMode: flexible

  showListFooter: true
  showBottomLine: true
  showCommandLog: true
  showPanelJumps: true

  showIcons: true
  nerdFontsVersion: "3"
  border: single
  theme:
    activeBorderColor:
      - blue
      - bold

git:
  autoFetch: true
  autoRefresh: true

  overrideGpg: true
  pagers:
    - colorArg: always
      pager: delta --features=lazygit-theme --paging=never --hyperlinks --hyperlinks-file-link-format="lazygit-edit://{path}:{line}"

    - pager: diff-so-fancy

    - {}

os:
  editInTerminal: true
  edit: '[ -z "$NVIM" ] && (nvim -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{filename}})'
  editAtLine: '[ -z "$NVIM" ] && (nvim +{{line}} -- {{filename}}) || (nvim --server "$NVIM" --remote-send "q" &&  nvim --server "$NVIM" --remote {{filename}} && nvim --server "$NVIM" --remote-send ":{{line}}<CR>")'
  openDirInEditor: '[ -z "$NVIM" ] && (nvim -- {{dir}}) || (nvim --server "$NVIM" --remote-send "q" && nvim --server "$NVIM" --remote {{dir}})'

keybinding:
  universal:
    undo: <alt+a>
    redo: <alt+d>
    scrollDownMain:
      - <pgdown>
      - J
      - <ctrl+d>
      - <ctrl+down>
    scrollUpMain:
      - <pgup>
      - K
      - <ctrl+u>
      - <ctrl+up>
  commits:
    moveDownCommit:
      - <ctrl+j>
      - <ctrl+alt-down>
    moveUpCommit:
      - <ctrl+k>
      - <ctrl+alt-up>
