general {
  before_sleep_cmd = swaylock -f -C ~/.config/swaylock/config
  after_sleep_cmd = hyprctl dispatch dpms on
  ignore_dbus_inhibit = false
  ignore_systemd_inhibit = false
  ignore_wayland_inhibit = false
  inhibit_sleep = 2
}

# Dim screen after 5 min
listener {
  timeout = 300
  on-timeout = sh -c 'brightnessctl -s set 10'
  on-resume = sh -c 'brightnessctl -r'
  ignore_inhibit = false
}

# Lock after 6 min
listener {
  timeout = 360
  on-timeout = swaylock -f -C ~/.config/swaylock/config
  ignore_inhibit = false
}

# Suspend after 7 min
listener {
  timeout = 420
  on-timeout = systemctl suspend
  ignore_inhibit = false
}
