general {
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch dpms on
  ignore_dbus_inhibit = false
  ignore_systemd_inhibit = false
}

listener {
  timeout = 480
  on-timeout = sh -c 'brightnessctl -s set 10 && hyprctl dispatch dpms off'
  on-resume = sh -c 'hyprctl dispatch dpms on && brightnessctl -r'
}

listener {
  timeout = 600
  on-timeout = swaylock -f -C ~/.config/swaylock/config
}

listener {
  timeout = 1200
  on-timeout = systemctl suspend
}

listener {
  timeout = 3600
  on-timeout = systemctl poweroff
}

