# core
source = ./core/programs.conf
source = ./core/autostart.conf
source = ./core/keybindings.conf
source = ./core/permission.conf

# appearance
source = ./appearance/windowrule.conf
source = ./appearance/lookNfeel.conf
source = ./appearance/animation.conf

# io
source = ./system/input.conf
source = ./system/monitors.conf
