max-gamma = 150

# Morning
profile {
    time = 08:00
    temperature = 6000
    gamma = 1
}

# Afternoon
profile {
    time = 14:00
    temperature = 4500
    gamma = 1
}

# Evening
profile {
    time = 19:00
    temperature = 3500
    gamma = 0.9
}
