# core
source = ./old/variable.conf
source = ./old/autostart.conf
source = ./old/environment.conf
source = ./old/keybind.conf
source = ./old/submap.conf
source = ./old/permission.conf

# appearance
source = ./old/windowrule.conf
source = ./old/lookNfeel.conf
source = ./old/animation.conf

# io
source = ./old/input.conf
source = ./old/monitor.conf
