general {
  lock_cmd = pidof swaylock || swaylock -f -C ~/.config/swaylock/config
  before_sleep_cmd = loginctl lock-session
  after_sleep_cmd = hyprctl dispatch dpms on
}

listener {
  timeout = 480 # 8 mins
  on-timeout = brightnessctl -s set 10
  on-resume = brightnessctl -r
}

listener {
  timeout = 600 # 10 mins
  on-timeout = loginctl lock-session
}

listener {
  timeout = 1200  # 20 mins
  on-timeout = systemctl suspend
}

listener {
  timeout = 3600 # 1 hr
  on-timeout = systemctl poweroff
}

