input {
  kb_layout = us
  kb_variant =
  kb_model =
  kb_options =
  kb_rules =

  float_switch_override_focus = 0
  follow_mouse = 1
  mouse_refocus = false
  numlock_by_default = false
  sensitivity = -0.6

  repeat_delay = 200
  repeat_rate = 40

  touchpad {
    natural_scroll = true
    disable_while_typing = true
    scroll_factor = 0.1
    tap-to-click = false
  }

  # This turns Caps Lock into an Escape key
  # Alternative: use keyd
  # kb_options = caps:escape
}

cursor {
  no_warps = true
  inactive_timeout = 10
}

