# This file sources other configuration files to keep things modular.
# symlinked to ~/.zshrc.
# The order of sourcing is critical!

# Basic shell setup - check if interactive
# =========================================================================
# Only load interactive-specific configurations in interactive shells.
# This prevents issues when running non-interactive scripts that start with zsh.
if [[ $- == *i* ]]; then

  # =================================================================
  # TMUX Session Manager
  # =================================================================

  # Only run session manager in real terminal, not in embedded IDE terminals
  if [[ $- == *i* ]] && [[ -z "$VSCODE_PID" ]] && [[ "$TERM_PROGRAM" != "vscode" ]]; then
    source ~/Arch-dotfiles/zsh/session-manager.zsh
  fi

  # if [[ -z "$TMUX" ]] && [[ $- == *i* ]]; then
  #   source ~/Arch-dotfiles/zsh/session-manager.zsh
  # fi

  # Instant Prompt (Powerlevel10k) - Load extremely early for perceived speed
  # =========================================================================
  # Load Powerlevel10k instant prompt cache. Keep this near the top!
  # This path is standard and typically outside the dotfiles directory.
  if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
    source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
  fi


  # Plugin Management (Antidote) and Completions
  # =========================================================================
  # Initialize Zsh's completion system.  
  autoload -Uz compinit
  compinit
  
  # Load Antidote from its installation directory.
  source ${ZDOTDIR:-~}/.antidote/antidote.zsh

  # Define the base directory for your Zsh configuration within your dotfiles.
  # Use ${ZDOTDIR:-$HOME} which correctly resolves to your home or ZDOTDIR.
  local dotfiles_zsh_dir="${ZDOTDIR:-$HOME}/Arch-dotfiles/zsh"

  # Path to plugin list and generated file.
  local plugins_txt_path="$dotfiles_zsh_dir/zsh_plugins.txt"
  local plugins_zsh_path="$dotfiles_zsh_dir/zsh_plugins.zsh"

  if [[ ! -f "$plugins_zsh_path" ]]; then
    echo "Generating $plugins_zsh_path..."
    if [[ -f "$plugins_txt_path" ]]; then
      antidote bundle < "$plugins_txt_path" > "$plugins_zsh_path"
      echo "Done generating plugins."
    else
      echo "Error: $plugins_txt_path not found! Cannot generate plugin sourcing file."
      echo "Please ensure $plugins_txt_path exists."
    fi
  fi
  # Source the file generated by Antidote which loads your plugins.
  source "$plugins_zsh_path" || echo "Error sourcing $plugins_zsh_path"

  compinit -D

  # Source Modular Configuration Files
  # =========================================================================
  # Define the base directory for your modular Zsh configuration files.
  local zsh_config_dir="$dotfiles_zsh_dir" # This is the same variable, just aliased for clarity if needed

  # Source the modular files in a logical sequence from the determined directory.
  if [[ -d "$zsh_config_dir" ]]; then
    # Order explained below, but roughly: Environment -> Behavior -> Commands -> Interactive
    source "$zsh_config_dir/path.zsh"         || echo "Error sourcing $zsh_config_dir/path.zsh"
    source "$zsh_config_dir/env_vars.zsh"     || echo "Error sourcing $zsh_config_dir/env_vars.zsh"
    source "$zsh_config_dir/setopt.zsh"       || echo "Error sourcing $zsh_config_dir/setopt.zsh"
    # Aliases and functions define commands. Source them after environment is ready.
    source "$zsh_config_dir/aliases.zsh"      || echo "Error sourcing $zsh_config_dir/aliases.zsh"
    source "$zsh_config_dir/functions.zsh"    || echo "Error sourcing $zsh_config_dir/functions.zsh"
    # Keybindings define interactive behavior, often relying on functions/aliases. Source last.
    source "$zsh_config_dir/keybindings.zsh"  || echo "Error sourcing $zsh_config_dir/keybindings.zsh"
  else
    echo "Warning: Modular Zsh config directory '$zsh_config_dir' not found. Skipping modular config."
    echo "Please ensure your Zsh dotfiles are in '$dotfiles_zsh_dir'."
  fi


  # Load Powerlevel10k config - Typically loaded last
  # =========================================================================
  # Source the Powerlevel10k configuration file. This applies prompt styles
  # after most other shell settings are established.
  # This file is typically located in your home directory (~/).
  [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh

fi # End of interactive shell check

# Any configuration that *must* run in non-interactive shells (e.g., basic PATH
# adjustments for scripts) would go here, outside the 'if' block. 

# =========================================================================
