# New window rule syntax
# Breaking change: 0.53

# Fixes
windowrule = match:class .*, suppress_event maximize
windowrule = match:class ^$ match:title ^$ match:xwayland true match:float true match:fullscreen false match:pin false, no_focus on

# Common Dialog Windows
windowrule {
    name = common-dialogs
    match:title = (Open File|Open Files|Save File|Open Folder|Choose Files|Choose Folder|Create Folder|Select Folder)

    float = on
    center = on
    size = 700 500
}

# File Operations
windowrule {
    name = file-ops
    match:title = ^(Rename|Move|File Operation Progress).*$

    float = on
    center = on
    size = 350 100
}

# Generic Dialogs
windowrule {
    name = generic-dialogs
    match:class = ^(.*)[Dd]ialog(.*)$

    float = on
    center = on
}

# XDG Desktop Portals
windowrule {
    name = xdg-portals
    match:class = ^(xdg-desktop-portal|org.freedesktop.portal).*$

    float = on
    center = on
    size = 700 500
}

# Workspace Rules
windowrule = match:title .* - Brave$, workspace 1
windowrule = match:initial_title ^(Visual Studio Code)$, workspace 3
windowrule = match:class ^(ONLYOFFICE)$, workspace 12
windowrule = match:class ^(Code)$, fullscreen_state -1 2

# KeePassXC
windowrule {
    name = keepass-popups
    match:title = ^(Generate Password).*$

    float = on
    center = on
}
