windowrule {
    name = DesktopEditors
    match:initial_class = ^.*(DesktopEditors).*$
    float = on
    center = on
    size = 570 120
}

windowrule {
    name = network-dialogs
    match:initial_class = ^.*(nm-connection-editor|blueman-manager).*$
    float = on
    center = on
    size = 800 500
}

windowrule {
    name = common-dialogs
    match:initial_title = ^.*(Open File|Open Files|Save File|Open Folder|Choose Files|Choose Folder|Create Folder|Select Folder|Open Document|Save As).*$
    float = on
    center = on
    size = 700 500
}

windowrule {
    name = file-ops
    match:initial_title = ^(Rename|Move|File Operation Progress).*$
    float = on
    center = on
    size = 350 130
}

# Web / Specific Popups
windowrule {
    name = export-download
    match:initial_title = ^.*(export-download|codeload|drive|wants to).*$

    float = on
    center = on
    size = 700 500
}

# Workspace Rules
windowrule = match:class ^brave-browser$, workspace 1
windowrule = match:class ^chromium$, workspace 5
windowrule = match:initial_class ^chrome-classroom.google.com__-Default$, workspace 5
windowrule = match:initial_class ^brave-music.youtube.com__-Default$, workspace 4

windowrule = match:initial_class ^com.obsproject.Studio$, workspace 3
windowrule = match:initial_title ^(Visual Studio Code)$, workspace 3
windowrule = match:class ^(ONLYOFFICE)$, workspace 3

windowrule = match:class ^(Code)$, fullscreen_state 2 2
