windowrule {
    name = network
    match:initial_class = ^.*(nm-connection-editor|blueman-manager).*$

    float = on
    center = on
    size = 800 500
}

# Common Dialog Windows
windowrule {
    name = common-dialogs
    match:initial_title = ^.*(Open File|Open Files|Save File|Open Folder|Choose Files|Choose Folder|Create Folder|Select Folder).*$

    float = on
    center = on
    size = 700 500
}

# File Operations
windowrule {
    name = file-ops
    match:initial_title = ^(Rename|Move|File Operation Progress).*$

    float = on
    center = on
    size = 350 100
}

# Web / Specific Popups
windowrule {
    name = export-download
    match:initial_title = ^.*(export-download|codeload|drive|wants to).*$

    float = on
    center = on
    size = 700 500
}

# Workspace Rules
windowrule = match:class ^brave-browser$, workspace 1
windowrule = match:initial_title ^(Visual Studio Code)$, workspace 3
windowrule = match:class ^(ONLYOFFICE)$, workspace 12
windowrule = match:class ^(Code)$, fullscreen_state 2 2
