# Fixes
windowrulev2 = suppressevent maximize,class:.*
windowrulev2 = nofocus,class:^$,title:^$,xwayland:1,floating:1,fullscreen:0,pinned:0

# Common Dialog Windows
windowrulev2 = float, title:(Open File|Open Files|Save File|Open Folder|Choose Files|Choose Folder|Create Folder|Select Folder)
windowrulev2 = center, title:(Open File|Open Files|Save File|Open Folder|Choose Files|Choose Folder|Create Folder|Select Folder)
windowrulev2 = size 700 500, title:(Open File|Open Files|Save File|Open Folder|Choose Files|Choose Folder|Create Folder|Select Folder)

# Other dialogs
windowrulev2 = float, title:^(Rename|Move|File Operation Progress).*$
windowrulev2 = center, title:^(Rename|Move|File Operation Progress).*$
windowrulev2 = size 350 100, title:^(Rename|Move|File Operation Progress).*$

# Generic dialog windows
windowrulev2 = float, class:^(.*)[Dd]ialog(.*)$
windowrulev2 = center, class:^(.*)[Dd]ialog(.*)$

# XDG Desktop Portals
windowrulev2 = float, class:^(xdg-desktop-portal).*$
windowrulev2 = float, class:^(org.freedesktop.portal).*$
windowrulev2 = center, class:^(xdg-desktop-portal).*$
windowrulev2 = center, class:^(org.freedesktop.portal).*$
windowrulev2 = size 700 500, class:^(xdg-desktop-portal).*$
windowrulev2 = size 700 500, class:^(org.freedesktop.portal).*$

# Workspace-Rules
windowrulev2 = workspace 1,title:.* - Brave$
windowrulev2 = workspace 3,initialTitle:^(Visual Studio Code)$
windowrulev2 = workspace 12,class:^(ONLYOFFICE)$
windowrulev2 = fullscreenstate -1 2, class:^(Code)$

# KeePassXC
windowrulev2 = float, title:^(Generate Password).*$
windowrulev2 = center, title:^(Generate Password).*$

