# Programs
$terminal = kitty
$browser = brave
$browserForSchool = google-chrome-stable --profile-directory="Profile 2"
$filemanager = thunar
$lockscreen = swaylock
$notifpanel = swaync-client -t
$colorpicker = hyprpicker -a
$record = obs --startrecording --minimize-to-tray
$ide = code
$passmanager = keepassxc

# Scripts
$launcher = "$HOME/Arch-dotfiles/rofi/launcher/launcher.sh"
$powermenu = "$HOME/Arch-dotfiles/rofi/powermenu/powermenu.sh"
$websearch = "$HOME/Arch-dotfiles/rofi/websearch/websearch.sh"

$screenshot = "$HOME/Arch-dotfiles/scripts/screenshot.sh"
$screenshotfull = "$HOME/Arch-dotfiles/scripts/screenshot-full.sh"
$ocr = "$HOME/Arch-dotfiles/scripts/ocr.sh"
$zen = "$HOME/Arch-dotfiles/scripts/toggle-zen.sh"
$mediactl = "$HOME/Arch-dotfiles/scripts/mediactl.sh"
$mouseclick = "$HOME/Arch-dotfiles/scripts/mouse-click.sh"
$eyetemp = "$HOME/Arch-dotfiles/scripts/toggle-hyprsunset.sh"
$zoom = "$HOME/Arch-dotfiles/scripts/zoom.sh"
